
export enum ProductQueues  {
    CREATE = 'PRODUCT_CREATE',
    READ = 'PRODUCT_READ',
    UPDATE = 'PRODUCT_UPDATE',
    DELETE = 'PRODUCT_DELETE',
    CONFIRM_CREATE = 'CONFIRM_PRODUCT_CREATE',
    CONFIRM_READ = 'CONFIRM_PRODUCT_READ',
    CONFIRM_UPDATE = 'CONFIRM_PRODUCT_UPDATE',
    CONFIRM_DELETE = 'CONFIRM_PRODUCT_DELETE'
}

